---
- name: Check if solr_home is already set up.
  stat: "path={{ solr_home }}/solr.xml"
  register: solr_develop

- name: Create SOLR data location
  file: "path={{ solr_home }}/{{ solr_core_name }}/data state=directory"

- name: Create SOLR core configuration location
  file: "path={{ solr_home }}/{{ solr_core_name }}/conf state=directory"

- name: Ensure solr_home directory exists.
  file:
    path: "{{ solr_home }}"
    state: directory
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    mode: 0755
  when: not solr_develop.stat.exists


- name: Copy SOLR Conf from files
  copy: "src=conf/* dest={{ solr_home }}/{{ solr_core_name }}/conf/"


- name: Ensure Solr home files are owned by the solr_user.
  file:
    path: "{{ solr_home }}"
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    recurse: yes
  when: not solr_develop.stat.exists
